senha:
	g++ salvaSenha.cpp -o senha
	./senha
teste:
	ag++ -c gerenc.cpp -o teste.acc -p. -a aspect.ah -w
	g++ teste.acc -o teste
	./teste
all:
	g++ salvaSenha.cpp -o senha
	./senha
	ag++ -c gerenc.cpp -o teste.acc -p. -a aspect.ah -w
	g++ teste.acc -o teste
	./teste